services:
  proxy:
    image: nginx:latest
    restart: unless-stopped
    volumes:
      - ./proxy/default.conf.template:/etc/nginx/templates/default.conf.template
    ports:
      - "80:80"

  hw1:
    image: httpd:latest
    restart: unless-stopped
    volumes:
      - ./Homework1:/usr/local/apache2/htdocs

  hw2:
    image: httpd:latest
    restart: unless-stopped
    volumes:
      - ./Homework2:/usr/local/apache2/htdocs

  hw3:
    build: ./Homework3
    restart: unless-stopped
    volumes:
      - ./Homework3/static:/app/hw3/static
      - ./Homework3/templates:/app/hw3/templates
      - ./Homework3/server.js:/app/hw3/server.js
    environment:
      - PORT=80

  hw4:
    build: ./Homework4
    restart: unless-stopped
    volumes:
      - ./Homework4/src:/app/hw4/src
      - ./Homework4/static:/app/hw4/static
      - ./Homework4/templates:/app/hw4/templates
      - ./Homework4/server.js:/app/hw4/server.js
    environment:
      - PORT=80

  hw5:
    build: ./Homework5
    restart: unless-stopped
    volumes:
      - ./Homework5/src:/app/hw5/src
      - ./Homework5/static:/app/hw5/static
      - ./Homework5/templates:/app/hw5/templates
      - ./Homework5/server.js:/app/hw5/server.js
    environment:
      - PORT=80